// Doubao / Dola API client. Wraps fetch() with:
//   - cookie / UA / origin / referer headers
//   - the standard query parameter set (version_code, device_id, …)
//   - real msToken (extracted from session cookie)
//   - real a_bogus (generated by bdms-sdk bytecode VM in a Node.js VM sandbox)
//   - X-Flow-Trace header

import * as crypto from 'node:crypto';
import { initSigner, addABogus, getLatestMsToken, resetSigner } from './bdms-signer.mjs';
import { bootstrapMsToken, getMsToken, setMsToken as setMsTokenCache } from './mstoken.mjs';

// Platform configuration
const PLATFORMS = {
  doubao: { origin: 'https://www.doubao.com', domain: 'www.doubao.com', envPrefix: 'DOUBAO' },
  dola:   { origin: 'https://www.dola.com',   domain: 'www.dola.com',   envPrefix: 'DOLA' },
};
let _platform = 'doubao';
let _platformCfg = PLATFORMS.doubao;

export function setPlatform(name) {
  const cfg = PLATFORMS[name];
  if (!cfg) throw new Error(`Unknown platform: ${name}`);
  _platform = name;
  _platformCfg = cfg;
}
export function getPlatformName() { return _platform; }
export function getPlatformOrigin() { return _platformCfg.origin; }

function envOrThrow(name) {
  const v = process.env[name];
  if (!v) throw new Error(`Missing env: ${name}. Run bootstrap() first or pass --env-file=.env.`);
  return v;
}

function envGet(name) {
  const prefix = _platformCfg.envPrefix;
  return process.env[`${prefix}_${name}`] || process.env[`DOUBAO_${name}`];
}
function envGetOrThrow(name) {
  const v = envGet(name);
  if (!v) throw new Error(`Missing env: ${_platformCfg.envPrefix}_${name} (or DOUBAO_${name}). Run bootstrap() first.`);
  return v;
}

export const env = {
  COOKIE: () => envGetOrThrow('COOKIE'),
  MS_TOKEN: () => generateMsToken(),
  UA: () => envGetOrThrow('USER_AGENT'),
  DEVICE_ID: () => envGetOrThrow('DEVICE_ID'),
  WEB_ID: () => envGetOrThrow('WEB_ID'),
  TEA_UUID: () => envGetOrThrow('TEA_UUID'),
  WEB_TAB_ID: () => envGetOrThrow('WEB_TAB_ID'),
  AID: () => envGetOrThrow('AID'),
  VERSION_CODE: () => envGetOrThrow('VERSION_CODE'),
  PC_VERSION: () => envGetOrThrow('PC_VERSION'),
  USER_ID: () => envGet('USER_ID') || '',
  FP: () => envGet('FP')
    || envGet('SAMANTHA_FP')
    || (envGet('COOKIE') || '').match(/s_v_web_id=([^;]+)/)?.[1]
    || '',
};

// msToken management: uses the centralized mstoken module for caching
// and rotation via x-ms-token response headers.
export function setMsToken(token) { setMsTokenCache(token); }

function generateFallbackMsToken() {
  return crypto.randomBytes(78).toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_') + '==';
}

function generateMsToken() {
  const explicit = envGet('MS_TOKEN');
  if (explicit) {
    setMsTokenCache(explicit);
    return explicit;
  }

  const cached = getMsToken();
  if (cached) return cached;

  const fromSigner = getLatestMsToken();
  if (fromSigner) {
    setMsTokenCache(fromSigner);
    return fromSigner;
  }

  const cookie = envGet('COOKIE') || '';
  const fromCookie = cookie.match(/(?:^|;\s*)msToken=([^;]+)/)?.[1];
  if (fromCookie) {
    setMsTokenCache(fromCookie);
    return fromCookie;
  }

  const fallback = generateFallbackMsToken();
  setMsTokenCache(fallback);
  return fallback;
}

export { generateMsToken };

// Initialize the bdms-sdk signer + msToken.
let _signerReady = false;
export async function ensureSignerReady() {
  if (_signerReady) return;
  await initSigner(env.COOKIE(), { platform: _platform, userAgent: env.UA(), platformName: /Macintosh|Mac OS X/i.test(env.UA()) ? 'MacIntel' : 'Win32' });
  await bootstrapMsToken();
  _signerReady = true;
}

export async function reinitForPlatform(platform) {
  setPlatform(platform);
  if (_signerReady) {
    resetSigner();
    _signerReady = false;
  }
  await ensureSignerReady();
}

// Build the standard query parameter set the web app sends on every API call.
// `extra` is merged on top.  Pass `flow: true` to use the chat/completion shape
// (uses fp= and key order as captured) instead of the IM shape.
export function queryFor(extra = {}, opts = {}) {
  const base = opts.flow
    ? {
        // /chat/completion uses an alphabetically sorted query string
        aid: env.AID(),
        device_id: env.DEVICE_ID(),
        device_platform: 'web',
        fp: env.FP(),
        language: 'zh',
        pc_version: env.PC_VERSION(),
        pkg_type: 'release_version',
        real_aid: env.AID(),
        region: 'JP',
        samantha_web: '1',
        sys_region: 'JP',
        tea_uuid: env.TEA_UUID(),
        'use-olympus-account': '1',
        version_code: env.VERSION_CODE(),
        web_id: env.WEB_ID(),
        web_platform: 'browser',
        web_tab_id: env.WEB_TAB_ID(),
      }
    : {
        version_code: env.VERSION_CODE(),
        language: 'zh',
        device_platform: 'web',
        aid: env.AID(),
        real_aid: env.AID(),
        pkg_type: 'release_version',
        device_id: env.DEVICE_ID(),
        pc_version: env.PC_VERSION(),
        web_id: env.WEB_ID(),
        tea_uuid: env.TEA_UUID(),
        region: 'JP',
        sys_region: 'JP',
        samantha_web: '1',
        'use-olympus-account': '1',
        web_tab_id: env.WEB_TAB_ID(),
      };

  const all = { ...base, ...extra };
  const usp = new URLSearchParams();
  for (const [k, v] of Object.entries(all)) {
    if (v === undefined || v === null) continue;
    usp.append(k, String(v));
  }
  return usp;
}

function normalizeSignedBody(body) {
  if (body == null) return '{}';
  return typeof body === 'string' ? body : JSON.stringify(body);
}

function randomHex(size) {
  return crypto.randomBytes(Math.ceil(size / 2)).toString('hex').slice(0, size);
}

function parseChromeMajorFromUA(ua) {
  const match = String(ua || '').match(/Chrome\/(\d+)/i);
  return match?.[1] || '149';
}

function platformHeaderFromUA(ua) {
  const override = envGet('SEC_CH_UA_PLATFORM');
  if (override) return override;
  const text = String(ua || '');
  if (/Macintosh|Mac OS X/i.test(text)) return '"macOS"';
  if (/Windows/i.test(text)) return '"Windows"';
  return '"macOS"';
}

function secChUaFromUA(ua) {
  const override = envGet('SEC_CH_UA');
  if (override) return override;
  const major = parseChromeMajorFromUA(ua);
  if (/Windows/i.test(String(ua || ''))) {
    return `"Chromium";v="${major}", "Google Chrome";v="${major}", "Not/A)Brand";v="99"`;
  }
  return `"Google Chrome";v="${major}", "Chromium";v="${major}", "Not)A;Brand";v="24"`;
}

function flowTraceHeader() {
  const override = envGet('FLOW_TRACE');
  if (override) return override;
  return `04-${randomHex(32)}-${randomHex(16)}-01`;
}

export function headersFor(opts = {}) {
  const ua = env.UA();
  const h = {
    'user-agent': ua,
    'cookie': env.COOKIE(),
    'accept': 'application/json, text/plain, */*',
    'accept-encoding': envGet('ACCEPT_ENCODING') || 'gzip, deflate, br',
    'accept-language': 'zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7',
    'cache-control': 'no-cache',
    'origin': _platformCfg.origin,
    'referer': opts.referer || `${_platformCfg.origin}/chat/`,
    'agw-js-conv': 'str, str',
    'x-flow-trace': flowTraceHeader(),
    'sec-ch-ua': secChUaFromUA(ua),
    'sec-ch-ua-platform': platformHeaderFromUA(ua),
    'sec-ch-ua-mobile': '?0',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'pragma': 'no-cache',
    'priority': 'u=1, i',
  };
  if (opts.json !== false) {
    h['content-type'] = opts.contentType || 'application/json';
  }
  return { ...h, ...(opts.extra || {}) };
}

function isFullUrl(u) {
  return /^https?:\/\//i.test(u);
}

// Build a raw URL with only the supplied extra query params — no msToken,
// a_bogus, version_code, etc.  Used for cookie-only endpoints like /top/v1.
export function buildRawUrl(pathOrUrl, extraQuery = {}) {
  let base, pathQuery;
  if (isFullUrl(pathOrUrl)) {
    const u = new URL(pathOrUrl);
    base = `${u.origin}${u.pathname}`;
    pathQuery = u.searchParams;
  } else {
    base = `${_platformCfg.origin}${pathOrUrl}`;
    pathQuery = new URLSearchParams();
  }
  for (const [k, v] of Object.entries(extraQuery)) {
    if (v === undefined || v === null) continue;
    pathQuery.set(k, String(v));
  }
  const qs = pathQuery.toString();
  return qs ? `${base}?${qs}` : base;
}

// Build the final URL with msToken + a_bogus appended.  `pathOrUrl` may be a
// full URL or a path on the current platform domain.  `extraQuery` is merged
// into the base query before signing.
export async function buildSignedUrl(pathOrUrl, method, extraQuery = {}, opts = {}) {
  let base, pathQuery;
  if (isFullUrl(pathOrUrl)) {
    const u = new URL(pathOrUrl);
    base = `${u.origin}${u.pathname}`;
    pathQuery = u.searchParams;
  } else {
    base = `${_platformCfg.origin}${pathOrUrl}`;
    pathQuery = new URLSearchParams();
  }

  const merged = queryFor({}, opts);
  for (const [k, v] of pathQuery.entries()) merged.set(k, v);
  for (const [k, v] of Object.entries(extraQuery)) {
    if (v === undefined || v === null) continue;
    merged.set(k, String(v));
  }
  merged.set('msToken', generateMsToken());

  const urlWithQuery = `${base}?${merged.toString()}`;
  return addABogus(urlWithQuery, method, normalizeSignedBody(opts.body));
}

// JSON request that returns parsed JSON (or throws on non-JSON / non-2xx).
// Set `init.raw: true` to skip the standard query block (version_code,
// device_id, msToken, a_bogus, …) — used for /top/v1 which the browser
// hits with only the ImageX action parameters and cookies.
export async function signedFetch(pathOrUrl, init = {}) {
  await ensureSignerReady();
  const method = (init.method || 'POST').toUpperCase();
  const body = init.body == null
    ? undefined
    : (typeof init.body === 'string' ? init.body : JSON.stringify(init.body));
  const url = init.raw
    ? buildRawUrl(pathOrUrl, init.query || {})
    : await buildSignedUrl(pathOrUrl, method, init.query || {}, { ...(init.flowQuery ? { flow: true } : {}), body });
  const headers = headersFor({ json: !!init.body, contentType: init.contentType, referer: init.referer, extra: init.headers });

  const timeoutMs = init.timeoutMs || 30000;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  const t0 = Date.now();
  let res;
  try {
    res = await fetch(url, { method, headers, body, signal: controller.signal });
  } catch (e) {
    if (e.name === 'AbortError') throw new Error(`HTTP timeout after ${timeoutMs}ms for ${pathOrUrl}`);
    throw e;
  } finally {
    clearTimeout(timer);
  }
  const dt = Date.now() - t0;
  // Capture rotated msToken from response
  const newMs = res.headers.get('x-ms-token');
  if (newMs) setMsToken(newMs);
  const text = await res.text();
  if (init.debug) console.error(`[signedFetch ${method} ${pathOrUrl}] ${res.status} ${dt}ms`);

  let json;
  try { json = JSON.parse(text); } catch {}
  if (!res.ok) {
    const err = new Error(`HTTP ${res.status} for ${pathOrUrl}: ${text.slice(0, 200)}`);
    err.status = res.status;
    err.body = text;
    err.json = json;
    throw err;
  }
  if (json === undefined) {
    const err = new Error(`Non-JSON response from ${pathOrUrl}: ${text.slice(0, 200)}`);
    err.body = text;
    throw err;
  }
  return json;
}

// SSE / streaming variant.  Returns the raw `Response`; caller iterates the
// body using `for await (const chunk of res.body)`.
export async function signedFetchSse(pathOrUrl, init = {}) {
  await ensureSignerReady();
  const method = (init.method || 'POST').toUpperCase();
  const body = init.body == null
    ? undefined
    : (typeof init.body === 'string' ? init.body : JSON.stringify(init.body));
  const url = await buildSignedUrl(pathOrUrl, method, init.query || {}, { ...(init.flowQuery ? { flow: true } : {}), body });
  const headers = headersFor({
    json: !!init.body,
    contentType: init.contentType,
    referer: init.referer,
    extra: { accept: 'text/event-stream', ...(init.headers || {}) },
  });

  const timeoutMs = init.timeoutMs || 45000;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  let res;
  try {
    res = await fetch(url, { method, headers, body, signal: controller.signal });
  } catch (e) {
    if (e.name === 'AbortError') throw new Error(`HTTP timeout after ${timeoutMs}ms for ${pathOrUrl}`);
    throw e;
  } finally {
    clearTimeout(timer);
  }
  const newMs = res.headers.get('x-ms-token');
  if (newMs) setMsToken(newMs);
  if (init.debug) console.error(`[signedFetchSse ${method} ${pathOrUrl}] ${res.status}`);
  return res;
}

// Async-iterate parsed SSE events (each event = { id, event, data }) from a
// streaming Response body.  `data` is the raw payload string.
export async function* parseSseStream(res) {
  if (!res.body) return;
  const reader = res.body.getReader();
  const decoder = new TextDecoder('utf-8');
  let buf = '';
  let evt = { id: '', event: '', data: '' };

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    buf += decoder.decode(value, { stream: true });

    let idx;
    while ((idx = buf.indexOf('\n')) !== -1) {
      const line = buf.slice(0, idx).replace(/\r$/, '');
      buf = buf.slice(idx + 1);

      if (line === '') {
        if (evt.event || evt.data) yield evt;
        evt = { id: '', event: '', data: '' };
        continue;
      }
      const m = line.match(/^([^:]+):\s?(.*)$/);
      if (!m) continue;
      const [, k, v] = m;
      if (k === 'id') evt.id = v;
      else if (k === 'event') evt.event = v;
      else if (k === 'data') evt.data = evt.data ? evt.data + '\n' + v : v;
    }
  }
  if (evt.event || evt.data) yield evt;
}

// Generate a UUID v4 (used for block_id, request-correlation IDs, etc.).
export function uuid() {
  return crypto.randomUUID();
}

// Generate a UUID v1 — what the Doubao web client uses for `local_message_id`.
// Shark fingerprints version-1 vs version-4: v4 from a "real" browser session
// is rejected on /chat/completion with ability_type=17.  Encodes 60-bit Unix
// 100ns timestamp + 14-bit clock seq + 48-bit pseudo-MAC.
const UUID_EPOCH_100NS = 0x01b21dd213814000n;
let _uuidV1ClockSeq = (Math.floor(Math.random() * 0x4000)) | 0;
const _uuidV1Node = (() => {
  const buf = crypto.randomBytes(6);
  buf[0] |= 0x01;
  return buf.toString('hex');
})();
function _hex(n, len) {
  return n.toString(16).padStart(len, '0').slice(-len);
}
export function uuidV1() {
  const ts100ns = BigInt(Date.now()) * 10000n + UUID_EPOCH_100NS;
  const timeLow  = Number(ts100ns & 0xffffffffn);
  const timeMid  = Number((ts100ns >> 32n) & 0xffffn);
  const timeHi   = Number((ts100ns >> 48n) & 0x0fffn) | 0x1000;
  _uuidV1ClockSeq = (_uuidV1ClockSeq + 1) & 0x3fff;
  const clockSeq = _uuidV1ClockSeq | 0x8000;
  return `${_hex(timeLow, 8)}-${_hex(timeMid, 4)}-${_hex(timeHi, 4)}-${_hex(clockSeq, 4)}-${_uuidV1Node}`;
}
